twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        main_menu:
            - { label: 'Créer un quiz', route: 'create' }
            - { label: 'Liste des quiz', route: 'quiz' }
            - { label: 'Répondre à un quiz', route: 'search_quiz' }