twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        header_menu_all:
            - { label: 'Accueil', route: 'home' }
        header_menu_deco:
            - { label: 'Inscription', route: 'security_registration' }
            - { label: 'Connexion', route: 'security_login' }
        header_menu_eleve:
            - { label: 'Répondre à un quiz', route: 'search_quiz' }
        header_menu_prof:
            - { label: 'Répondre à un quiz', route: 'search_quiz' }
            - { label: 'Créer un quiz', route: 'create' }
            - { label: 'Liste des quiz', route: 'quiz' }
        header_menu_co:
            - { label: 'Deconnexion', route: 'security_logout' }