twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        main_menu:
            - { label: 'Accueil', route: '' }
            - { label: 'Mon compte', route: '' }
            - { label: 'Inscription', route: '' }
            - { label: 'Connexion', route: '' }